### PR TITLE
Move to Heroku

### PR DESCRIPTION
**Pull request by georgeclaghorn**
We've only really used the club's Digital Ocean cluster for Handy since its creation. Heroku can provide everything Handy needs for free, and with less maintenance required.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
:pray:

**Comment by georgeclaghorn** [comment]
No, since Handy spends most of its time idle. It won't come close to the 18-hour maximum uptime per 24-hour period.

**Comment by alexlafroscia** [comment]
Sweet

**Comment by georgeclaghorn** [comment]
@jroggeman: This seem okay to you? If so, I'll merge this tonight and give you and @alexlafroscia push access to the Heroku app.

**Pull request merged**
